import React, { useState } from 'react'
import Head from 'next/head'
import ExampleModal from './ExampleModal';


const ListCredentials = () => {
  const [ID, setID] = useState('')
  const [message, setMessage] = useState('')

  let handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault()
    try {
      let res = await fetch(
        `https://butq3lt5uk.execute-api.eu-west-2.amazonaws.com/stage/users/${ID}`,
        {
          method: 'GET',
          headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
          },
        },
      )
      let resJson = await res.json()
      if (res.status === 200) {
        setID('')
        setMessage('Credentials are:abcdefghij')
       // alert(`Generated credentials are: ${message}`)
      } else {
        setMessage('Some error occurred')
      }
    } catch (err) {
      console.log(err)
    }
  }
  return (
    <div>
      <Head>
        <title>User Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 id="title">List All Credentials</h1>
        </div>

        <br></br>

        <div style={{ display: 'flex', justifyContent: 'center' ,textAlign: 'center'}}>
          <form onSubmit={handleSubmit}>
            <p>Input the Tenant ID</p>
            <br></br>
            <input
              type="text"
              value={ID}
              placeholder="Tenant ID"
              onChange={(e) => setID(e.target.value)}
              style={{ margin: '0 auto' }}
            />

            <br></br>

            <button type="submit" style={{ backgroundColor: '#008080' , margin: '0 auto'}}>
              List Credentials
            </button>

            <div className="message">{message ? <p>{message}</p> : null}</div>
          </form>
        </div>
      </main>
    </div>
  )
}

export default ListCredentials
