import React, { useState } from 'react'
import Head from 'next/head'

const DeleteIndex = () => {
  const [name, setName] = useState('')
  const [message, setMessage] = useState('')

  let handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault()
    try {
      let res = await fetch(
        `https://butq3lt5uk.execute-api.eu-west-2.amazonaws.com/stage/users/${name}`,
        {
          method: 'DELETE',
          headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
          },
        },
      )
      let resJson = await res.json()
      if (res.status === 200) {
        setName('')
        setMessage('Index deleted successfully')
      } else {
        setMessage('Some error occurred')
      }
    } catch (err) {
      console.log(err)
    }
  }
  return (
    <div>
      <Head>
        <title>Opensearch Index Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 id="title">Delete OpenSearch Index</h1>
        </div>

        <br></br>

        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <form onSubmit={handleSubmit}>
            <p>Input name of the index you want to delete</p>
            <br></br>
            <input
              type="text"
              value={name}
              placeholder="Index Name"
              onChange={(e) => setName(e.target.value)}
            />

            <br></br>

            <button type="submit" style={{ backgroundColor: '#008080' }}>
              Delete Index
            </button>

            <div className="message">{message ? <p>{message}</p> : null}</div>
          </form>
        </div>
      </main>
    </div>
  )
}

export default DeleteIndex
