import React, { useState } from 'react'
import Head from 'next/head'

const SearchUser = () => {
  const [id, setTenantId] = useState('')
  const [name, setIndexName] = useState('')
  const [shards, setShardsCount] = useState('')
  const [replicas, setReplicasCount] = useState('')
  const [message, setMessage] = useState('')

  let handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault()
    try {
      let res = await fetch(
        `https://butq3lt5uk.execute-api.eu-west-2.amazonaws.com/stage/users/${name}`,
        {
          method: 'GET',
          headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
          },
        },
      )
      let resJson = await res.json()

      if (res.status === 200) {
        setIndexName('')
        setMessage('User found successfully')
        console.log(resJson.data.data)
        setTenantId(resJson.data.data)
        setIndexName(resJson.data.data.name)
        setShardsCount(resJson.data.data.email)
        setReplicasCount(resJson.data.data.phone)
      } else {
        setMessage('Some error occurred')
      }
    } catch (err) {
      console.log(err)
    }
  }
  return (
    <div>
      <Head>
        <title>Opensearch Index Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 id="title">Search Index</h1>
        </div>

        <br></br>

        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <form onSubmit={handleSubmit}>
            <p>Input name of the Index you want to search</p>
            <br></br>
            <input
              type="text"
              value={name}
              placeholder="Index Name"
              onChange={(e) => setIndexName(e.target.value)}
            />

            <br></br>

            <button type="submit" style={{ backgroundColor: '#008080' }}>
              List Documents
            </button>

            <div className="message">{message ? <p>{message}</p> : null}</div>
          </form>
        </div>

        <br></br>

        <div className="user-details-container">
          {/* {user.id && <p style={{ display: 'flex', justifyContent: 'center'}}>ID: {user.id}</p>} */}
          {name && (
            <p style={{ display: 'flex', justifyContent: 'center' }}>
              Name: {name}
            </p>
          )}
          {id && (
            <p style={{ display: 'flex', justifyContent: 'center' }}>
              Tenant Is: {id}
            </p>
          )}
          {shards && (
            <p style={{ display: 'flex', justifyContent: 'center' }}>
              Number of Shards: {shards}
            </p>
          )}
          {replicas && (
            <p style={{ display: 'flex', justifyContent: 'center' }}>
              Number of Replicas: {replicas}
            </p>
          )}
        </div>
      </main>
    </div>
  )
}

export default SearchUser
